### PR TITLE
ADD GOEOBOT BEST BOT :D

### PR DESCRIPTION
**Pull request by mayacopeland**
[ 68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966 ](https://camo.githubusercontent.com/92414bb1b7af756d07d15649e316a08669ba7d198340649382c204b621e5e9b4/68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966) [ ](https://camo.githubusercontent.com/92414bb1b7af756d07d15649e316a08669ba7d198340649382c204b621e5e9b4/68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966)

### CODE REVIEW

**Review by jacksonisiah — CHANGES_REQUESTED** [review]
Table spacing

**Review by NiceAesth — COMMENTED** [review]
fast merging

**Comment by mayacopeland** [comment]
WHERE FAST MERGING

**Review by jacksonisiah — APPROVED** [review]

**Review by NiceAesth — APPROVED** [review]
FASTRP

**Comment by mayacopeland** [comment]
[ 68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966 ](https://camo.githubusercontent.com/92414bb1b7af756d07d15649e316a08669ba7d198340649382c204b621e5e9b4/68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966) [ ](https://camo.githubusercontent.com/92414bb1b7af756d07d15649e316a08669ba7d198340649382c204b621e5e9b4/68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966)

**Pull request merged**
