### PR TITLE
Reformat, lint, and add more projects

### PR DESCRIPTION
**Pull request by jacksonisiah**
title

### CODE REVIEW

**Review by NiceAesth — DISMISSED** [review]
Looks fine to me other than what I mentioned on Discord.

**Comment by jacksonisiah** [comment]
Putting in a vote for using reference links throughout. Upside is the document looks really pretty in the editor, and makes more sense. Downside is it may confuse newer markdown users.
@NiceAesth @aeongdesu

**Review by NiceAesth — DISMISSED** [review]
I don't really care about the downside when it is this easy to understand, fine by me.

**Comment by jacksonisiah** [comment]
As discussed on discord the `soft-wrap` method pretty much solves the problem without the extra work 🐱

**Pull request merged**
