### PR TITLE
Add mirria to beatmap mirror list.

### PR DESCRIPTION
**Pull request by DHCPCD9**
Look at the title

### CODE REVIEW

**Comment by NiceAesth** [comment]
the url goes to a discord server. is that intended?

**Comment by DHCPCD9** [comment]
> the url goes to a discord server. is that intended?

Yes, server contains API documentation and related to mirror information.

**Comment by NiceAesth** [comment]
yeah, would prefer it to be a link to the mirror website instead not some random discord server

**Comment by NiceAesth** [comment]
@jacksonisiah going to ask for ur opinion as well if you're fine with it i'm fine with it

**Comment by jacksonisiah** [comment]
@DHCPCD9 this randomly showed up in my github inbox months later, is this mirror still active? apologies for the long lead time

**Pull request closed without merging**
